global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: go-service
    metrics_path: /metrics
    static_configs:
      - targets: ["go-service:8080"]
        labels:
          service: go-service
