name: CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: go-service
            context: go-service
            dockerfile: go-service/Dockerfile
          - name: python-service
            context: python-service
            dockerfile: python-service/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Optional login to Docker Hub
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Go - setup
        if: ${{ matrix.service.name == 'go-service' }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Go - test
        if: ${{ matrix.service.name == 'go-service' }}
        run: |
          go mod download
          go test ./...
        working-directory: ${{ matrix.service.context }}

      - name: Python - setup
        if: ${{ matrix.service.name == 'python-service' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Python - install deps
        if: ${{ matrix.service.name == 'python-service' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m compileall .
        working-directory: ${{ matrix.service.context }}

      - name: Docker metadata (GHCR)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ matrix.service.name }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.service.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Optional push to Docker Hub
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.service.dockerfile }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:${{ github.sha }}
